PLUGIN_NAME=		siem-lite
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Lightweight SIEM with log correlation, Sigma rules and security analytics
PLUGIN_MAINTAINER=	kuiper@local
PLUGIN_WWW=		https://opnsense.org

.include "../../Mk/plugins.mk"
