#!/usr/local/bin/python3

"""
SIEM-Lite: Lightweight Security Information and Event Management for OPNsense
Main engine - handles log collection, parsing, Sigma rule evaluation,
event correlation, alerting, and database management.

Copyright (C) 2024 Kuiper
All rights reserved.
"""

import json
import os
import re
import sqlite3
import sys
import time
import hashlib
import signal
import socket
import urllib.request
import logging
from datetime import datetime, timedelta
from pathlib import Path

DB_PATH = '/var/db/siemlite/siem.db'
PID_FILE = '/var/run/siemlite.pid'
CONFIG_PATH = '/usr/local/etc/siemlite/settings.json'
BUILTIN_RULES_PATH = '/usr/local/opnsense/scripts/OPNsense/SIEMLite/builtin_rules.json'

LOG_SOURCES = {
    'firewall': '/var/log/filter/latest.log',
    'ids': '/var/log/suricata/eve.json',
    'proxy': '/var/log/squid/access.log',
    'vpn': '/var/log/openvpn/latest.log',
    'auth': '/var/log/auth.log',
    'system': '/var/log/system/latest.log',
    'webui': '/var/log/lighttpd/latest.log',
    'cron': '/var/log/cron/latest.log',
}

# Ensure log directory exists before configuring logging
os.makedirs('/var/log/siemlite', exist_ok=True)
os.makedirs('/var/db/siemlite', exist_ok=True)

logging.basicConfig(
    filename='/var/log/siemlite/siemlite.log',
    level=logging.INFO,
    format='%(asctime)s %(levelname)s %(message)s'
)
log = logging.getLogger('siemlite')


def init_db():
    """Initialize SQLite database with WAL mode for concurrent access."""
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=NORMAL")
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            source TEXT NOT NULL,
            severity TEXT DEFAULT 'informational',
            src_ip TEXT,
            src_port TEXT,
            dst_ip TEXT,
            dst_port TEXT,
            protocol TEXT,
            interface TEXT,
            action TEXT,
            message TEXT,
            raw TEXT,
            country TEXT,
            matched_rule TEXT,
            mitre_tactic TEXT,
            mitre_technique TEXT,
            created_at REAL NOT NULL
        );

        CREATE TABLE IF NOT EXISTS alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            severity TEXT NOT NULL,
            rule_title TEXT NOT NULL,
            rule_id TEXT,
            source TEXT,
            src_ip TEXT,
            dst_ip TEXT,
            message TEXT,
            event_count INTEGER DEFAULT 1,
            status TEXT DEFAULT 'new',
            mitre TEXT,
            created_at REAL NOT NULL,
            updated_at REAL
        );

        CREATE TABLE IF NOT EXISTS log_positions (
            source TEXT PRIMARY KEY,
            position INTEGER DEFAULT 0,
            inode INTEGER DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS risk_history (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            score INTEGER NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events(timestamp);
        CREATE INDEX IF NOT EXISTS idx_events_source ON events(source);
        CREATE INDEX IF NOT EXISTS idx_events_severity ON events(severity);
        CREATE INDEX IF NOT EXISTS idx_events_src_ip ON events(src_ip);
        CREATE INDEX IF NOT EXISTS idx_events_created ON events(created_at);
        CREATE INDEX IF NOT EXISTS idx_alerts_timestamp ON alerts(timestamp);
        CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity);
        CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
    """)
    conn.commit()
    return conn


def load_config():
    """Load configuration from settings.json generated by configd template."""
    try:
        with open(CONFIG_PATH, 'r') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


# ─── Log Parsers ─────────────────────────────────────────────────────────────

def parse_filterlog(line):
    """Parse OPNsense filterlog CSV format."""
    parts = line.split(',')
    if len(parts) < 20:
        return None

    event = {
        'source': 'firewall',
        'interface': parts[4] if len(parts) > 4 else '',
        'action': parts[6] if len(parts) > 6 else '',
        'protocol': parts[16] if len(parts) > 16 else '',
    }

    # IPv4 fields
    if len(parts) > 18:
        event['src_ip'] = parts[18]
    if len(parts) > 19:
        event['dst_ip'] = parts[19]

    # TCP/UDP ports
    proto = event['protocol'].lower()
    if proto in ('tcp', 'udp') and len(parts) > 21:
        event['src_port'] = parts[20] if len(parts) > 20 else ''
        event['dst_port'] = parts[21] if len(parts) > 21 else ''

    action = event['action'].lower()
    if action == 'block':
        event['severity'] = 'low'
        event['message'] = f"Blocked {event['protocol']} {event.get('src_ip','')}:{event.get('src_port','')} → {event.get('dst_ip','')}:{event.get('dst_port','')}"
    else:
        event['severity'] = 'informational'
        event['message'] = f"Passed {event['protocol']} {event.get('src_ip','')} → {event.get('dst_ip','')}"

    return event


def parse_suricata_eve(line):
    """Parse Suricata EVE JSON format."""
    try:
        data = json.loads(line)
    except json.JSONDecodeError:
        return None

    event = {
        'source': 'ids',
        'src_ip': data.get('src_ip', ''),
        'dst_ip': data.get('dest_ip', ''),
        'src_port': str(data.get('src_port', '')),
        'dst_port': str(data.get('dest_port', '')),
        'protocol': data.get('proto', ''),
    }

    event_type = data.get('event_type', '')
    if event_type == 'alert':
        alert = data.get('alert', {})
        severity_map = {1: 'critical', 2: 'high', 3: 'medium'}
        event['severity'] = severity_map.get(alert.get('severity', 3), 'low')
        event['message'] = alert.get('signature', 'IDS Alert')
        event['action'] = alert.get('action', 'alert')
        event['matched_rule'] = alert.get('signature_id', '')
    elif event_type == 'dns':
        event['severity'] = 'informational'
        dns = data.get('dns', {})
        event['message'] = f"DNS {dns.get('type','query')}: {dns.get('rrname','')}"
    elif event_type == 'tls':
        event['severity'] = 'informational'
        tls = data.get('tls', {})
        event['message'] = f"TLS: {tls.get('sni','unknown')} ({tls.get('version','')})"
    else:
        event['severity'] = 'informational'
        event['message'] = f"Suricata {event_type}"

    return event


def parse_squid(line):
    """Parse Squid access log format."""
    parts = line.split()
    if len(parts) < 10:
        return None

    event = {
        'source': 'proxy',
        'severity': 'informational',
        'src_ip': parts[2] if len(parts) > 2 else '',
        'action': parts[3] if len(parts) > 3 else '',
        'message': f"{parts[5]} {parts[6]}" if len(parts) > 6 else line[:200],
    }

    status_code = parts[3].split('/')[1] if '/' in parts[3] else ''
    if status_code.startswith('4') or status_code.startswith('5'):
        event['severity'] = 'low'
    if 'DENIED' in line:
        event['severity'] = 'medium'
        event['action'] = 'denied'

    return event


def parse_auth(line):
    """Parse authentication log entries."""
    event = {
        'source': 'auth',
        'severity': 'informational',
        'message': line[:500],
    }

    # Extract IP from common patterns
    ip_match = re.search(r'from\s+(\d+\.\d+\.\d+\.\d+)', line)
    if ip_match:
        event['src_ip'] = ip_match.group(1)

    lower = line.lower()
    if 'failed' in lower or 'invalid' in lower or 'error' in lower:
        event['severity'] = 'medium'
        event['action'] = 'failed'
        if 'repeated' in lower or 'multiple' in lower:
            event['severity'] = 'high'
    elif 'accepted' in lower or 'success' in lower:
        event['action'] = 'success'
    elif 'sudo' in lower:
        event['severity'] = 'low'
        event['action'] = 'sudo'
        if 'incorrect' in lower:
            event['severity'] = 'high'

    return event


def parse_generic(line, source_name):
    """Generic parser for system, webui, cron, openvpn logs."""
    event = {
        'source': source_name,
        'severity': 'informational',
        'message': line[:500],
    }

    ip_match = re.search(r'(\d+\.\d+\.\d+\.\d+)', line)
    if ip_match:
        event['src_ip'] = ip_match.group(1)

    lower = line.lower()
    if any(w in lower for w in ('error', 'fail', 'denied', 'refused', 'attack')):
        event['severity'] = 'medium'
        event['action'] = 'error'
    elif any(w in lower for w in ('warn', 'timeout', 'retry')):
        event['severity'] = 'low'
        event['action'] = 'warning'

    return event


PARSERS = {
    'firewall': parse_filterlog,
    'ids': parse_suricata_eve,
    'proxy': parse_squid,
    'auth': parse_auth,
    'vpn': lambda l: parse_generic(l, 'vpn'),
    'system': lambda l: parse_generic(l, 'system'),
    'webui': lambda l: parse_generic(l, 'webui'),
    'cron': lambda l: parse_generic(l, 'cron'),
}


# ─── Log Collector ───────────────────────────────────────────────────────────

def collect_logs(conn, config):
    """Read new lines from all enabled log sources."""
    cursor = conn.cursor()
    now = time.time()
    timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')
    new_events = []

    for source, logfile in LOG_SOURCES.items():
        if not config.get(f'source_{source}', '0') == '1':
            continue
        if not os.path.exists(logfile):
            continue

        try:
            stat = os.stat(logfile)
            inode = stat.st_ino

            cursor.execute("SELECT position, inode FROM log_positions WHERE source = ?", (source,))
            row = cursor.fetchone()
            old_pos = row[0] if row else 0
            old_inode = row[1] if row else 0

            # File rotated?
            if inode != old_inode:
                old_pos = 0

            with open(logfile, 'r', errors='replace') as f:
                f.seek(old_pos)
                lines = f.readlines()
                new_pos = f.tell()

            parser = PARSERS.get(source)
            if not parser:
                continue

            batch = []
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                event = parser(line)
                if not event:
                    continue
                event['raw'] = line[:2000]
                event['timestamp'] = timestamp
                event['created_at'] = now
                batch.append(event)

            if batch:
                cursor.executemany("""
                    INSERT INTO events (timestamp, source, severity, src_ip, src_port,
                        dst_ip, dst_port, protocol, interface, action, message, raw,
                        matched_rule, mitre_tactic, mitre_technique, created_at)
                    VALUES (:timestamp, :source, :severity, :src_ip, :src_port,
                        :dst_ip, :dst_port, :protocol, :interface, :action, :message, :raw,
                        :matched_rule, :mitre_tactic, :mitre_technique, :created_at)
                """, [{
                    'timestamp': e.get('timestamp', timestamp),
                    'source': e.get('source', source),
                    'severity': e.get('severity', 'informational'),
                    'src_ip': e.get('src_ip', ''),
                    'src_port': e.get('src_port', ''),
                    'dst_ip': e.get('dst_ip', ''),
                    'dst_port': e.get('dst_port', ''),
                    'protocol': e.get('protocol', ''),
                    'interface': e.get('interface', ''),
                    'action': e.get('action', ''),
                    'message': e.get('message', ''),
                    'raw': e.get('raw', ''),
                    'matched_rule': e.get('matched_rule', ''),
                    'mitre_tactic': e.get('mitre_tactic', ''),
                    'mitre_technique': e.get('mitre_technique', ''),
                    'created_at': e.get('created_at', now),
                } for e in batch])
                new_events.extend(batch)

            # Update position
            if row:
                cursor.execute("UPDATE log_positions SET position = ?, inode = ? WHERE source = ?",
                             (new_pos, inode, source))
            else:
                cursor.execute("INSERT INTO log_positions (source, position, inode) VALUES (?, ?, ?)",
                             (source, new_pos, inode))

        except Exception as ex:
            log.error(f"Error collecting {source}: {ex}")

    conn.commit()
    return new_events


# ─── Sigma Rule Engine ───────────────────────────────────────────────────────

def load_sigma_rules():
    """Load active Sigma rules from OPNsense config via configd."""
    try:
        import subprocess
        result = subprocess.run(
            ['/usr/local/sbin/configctl', 'siemlite', 'get-rules'],
            capture_output=True, text=True, timeout=10
        )
        rules = json.loads(result.stdout)
        return [r for r in rules if r.get('enabled', '0') == '1']
    except Exception as ex:
        log.error(f"Error loading Sigma rules: {ex}")
        return []


def evaluate_rules(conn, events, rules, config):
    """Evaluate Sigma rules against new events and generate alerts."""
    if not rules or not events:
        return

    cursor = conn.cursor()
    now = time.time()
    timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')
    correlation_window = int(config.get('correlation_window', 300))

    for rule in rules:
        source_filter = rule.get('logsource', 'any')
        condition = rule.get('condition', 'contains')
        pattern = rule.get('detection_pattern', '')
        threshold = int(rule.get('threshold', 1))
        timewindow = int(rule.get('timewindow', 300))

        # Filter events by source
        if source_filter != 'any':
            source_map = {
                'firewall': 'firewall', 'ids': 'ids', 'proxy': 'proxy',
                'vpn': 'vpn', 'auth': 'auth', 'system': 'system', 'webui': 'webui'
            }
            target_source = source_map.get(source_filter, source_filter)
            matched_events = [e for e in events if e.get('source') == target_source]
        else:
            matched_events = events

        if not matched_events:
            continue

        match_count = 0
        matched_ips = set()

        for event in matched_events:
            raw = event.get('raw', '') + ' ' + event.get('message', '')
            hit = False

            if condition == 'contains':
                hit = pattern.lower() in raw.lower()
            elif condition == 'regex':
                try:
                    hit = bool(re.search(pattern, raw, re.IGNORECASE))
                except re.error:
                    pass
            elif condition in ('count_gt', 'count_lt', 'frequency'):
                hit = True  # Count all matching source events

            if hit:
                match_count += 1
                if event.get('src_ip'):
                    matched_ips.add(event['src_ip'])

        # Check thresholds
        triggered = False
        if condition == 'contains' and match_count >= threshold:
            triggered = True
        elif condition == 'regex' and match_count >= threshold:
            triggered = True
        elif condition == 'count_gt' and match_count > threshold:
            triggered = True
        elif condition == 'count_lt' and match_count < threshold:
            triggered = True
        elif condition == 'frequency':
            # Check frequency within time window from DB
            since = now - timewindow
            cursor.execute("""
                SELECT COUNT(*) FROM events
                WHERE source = ? AND created_at >= ? AND
                (message LIKE ? OR raw LIKE ?)
            """, (
                source_filter if source_filter != 'any' else '%',
                since,
                f'%{pattern}%', f'%{pattern}%'
            ))
            db_count = cursor.fetchone()[0]
            if db_count >= threshold:
                triggered = True
                match_count = db_count

        if triggered:
            # Deduplicate: don't alert if same rule fired within window
            cursor.execute("""
                SELECT id FROM alerts
                WHERE rule_id = ? AND created_at >= ?
                AND status != 'closed'
            """, (rule.get('uuid', rule.get('title', '')), now - timewindow))

            existing = cursor.fetchone()
            if existing:
                # Update event count
                cursor.execute("UPDATE alerts SET event_count = event_count + ?, updated_at = ? WHERE id = ?",
                             (match_count, now, existing[0]))
            else:
                mitre = ''
                if rule.get('mitre_tactic'):
                    mitre = rule['mitre_tactic']
                    if rule.get('mitre_technique'):
                        mitre += '/' + rule['mitre_technique']

                cursor.execute("""
                    INSERT INTO alerts (timestamp, severity, rule_title, rule_id, source,
                        src_ip, message, event_count, status, mitre, created_at, updated_at)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'new', ?, ?, ?)
                """, (
                    timestamp,
                    rule.get('severity', 'medium'),
                    rule.get('title', 'Unknown Rule'),
                    rule.get('uuid', ''),
                    source_filter,
                    ', '.join(list(matched_ips)[:5]),
                    f"Rule '{rule.get('title','')}' triggered: {match_count} matching events",
                    match_count,
                    mitre,
                    now, now
                ))

                log.info(f"ALERT: {rule.get('severity','medium').upper()} - {rule.get('title','')} "
                        f"({match_count} events, IPs: {', '.join(list(matched_ips)[:3])})")

                # Send notifications
                send_notifications(rule, match_count, matched_ips, config)

    conn.commit()


# ─── Notification Engine ─────────────────────────────────────────────────────

def send_notifications(rule, count, ips, config):
    """Send alert notifications via configured channels."""
    severity = rule.get('severity', 'medium')
    severity_order = {'low': 0, 'medium': 1, 'high': 2, 'critical': 3}
    sev_val = severity_order.get(severity, 0)

    title = rule.get('title', 'Unknown')
    msg = f"[SIEM-Lite] {severity.upper()}: {title} ({count} events, IPs: {', '.join(list(ips)[:3])})"

    # Webhook
    if config.get('webhook_enabled', '0') == '1':
        min_sev = severity_order.get(config.get('webhook_min_severity', 'medium'), 1)
        if sev_val >= min_sev:
            try:
                url = config.get('webhook_url', '')
                if url:
                    payload = json.dumps({
                        'text': msg,
                        'severity': severity,
                        'rule': title,
                        'event_count': count,
                        'source_ips': list(ips)[:10],
                        'mitre_tactic': rule.get('mitre_tactic', ''),
                        'mitre_technique': rule.get('mitre_technique', ''),
                        'timestamp': datetime.utcnow().isoformat()
                    }).encode('utf-8')
                    req = urllib.request.Request(url, data=payload,
                        headers={'Content-Type': 'application/json'})
                    urllib.request.urlopen(req, timeout=10)
            except Exception as ex:
                log.error(f"Webhook notification failed: {ex}")

    # Syslog
    if config.get('syslog_enabled', '0') == '1':
        min_sev = severity_order.get(config.get('syslog_min_severity', 'low'), 0)
        if sev_val >= min_sev:
            try:
                host = config.get('syslog_host', '')
                port = int(config.get('syslog_port', 514))
                proto = config.get('syslog_protocol', 'udp')
                if host:
                    syslog_msg = f"<{14 - sev_val * 2}>siemlite: {msg}"
                    if proto == 'udp':
                        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                        sock.sendto(syslog_msg.encode('utf-8'), (host, port))
                        sock.close()
                    else:
                        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                        sock.settimeout(5)
                        sock.connect((host, port))
                        sock.sendall(syslog_msg.encode('utf-8') + b'\n')
                        sock.close()
            except Exception as ex:
                log.error(f"Syslog notification failed: {ex}")


# ─── Maintenance ─────────────────────────────────────────────────────────────

def prune_old_data(conn, config):
    """Remove events older than retention period or exceeding max count."""
    retention_days = int(config.get('retention_days', 30))
    max_events = int(config.get('max_events', 500000))
    cutoff = time.time() - (retention_days * 86400)

    cursor = conn.cursor()
    cursor.execute("DELETE FROM events WHERE created_at < ?", (cutoff,))
    deleted_time = cursor.rowcount

    # Enforce max events
    cursor.execute("SELECT COUNT(*) FROM events")
    total = cursor.fetchone()[0]
    if total > max_events:
        excess = total - max_events
        cursor.execute("DELETE FROM events WHERE id IN (SELECT id FROM events ORDER BY created_at ASC LIMIT ?)",
                      (excess,))

    # Prune old risk history
    cursor.execute("DELETE FROM risk_history WHERE timestamp < ?",
                  ((datetime.utcnow() - timedelta(days=90)).strftime('%Y-%m-%d %H:%M:%S'),))

    conn.commit()
    if deleted_time > 0:
        log.info(f"Pruned {deleted_time} events older than {retention_days} days")


def calculate_risk_score(conn, config):
    """Calculate current risk score based on active alerts."""
    cursor = conn.cursor()
    since = time.time() - 86400  # last 24h

    weights = {'critical': 25, 'high': 15, 'medium': 5, 'low': 1}
    score = 0

    for severity, weight in weights.items():
        cursor.execute(
            "SELECT COUNT(*) FROM alerts WHERE severity = ? AND status != 'closed' AND created_at >= ?",
            (severity, since)
        )
        count = cursor.fetchone()[0]
        score += count * weight

    score = min(100, score)

    # Record in history
    cursor.execute("INSERT INTO risk_history (timestamp, score) VALUES (?, ?)",
                  (datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S'), score))
    conn.commit()
    return score


# ─── Main Loop ───────────────────────────────────────────────────────────────

def run_daemon():
    """Main SIEM-Lite daemon loop."""
    os.makedirs('/var/log/siemlite', exist_ok=True)
    os.makedirs('/var/db/siemlite', exist_ok=True)

    conn = init_db()
    config = load_config()

    running = True
    def handle_signal(signum, frame):
        nonlocal running
        running = False
        log.info("Received signal, shutting down")

    signal.signal(signal.SIGTERM, handle_signal)
    signal.signal(signal.SIGINT, handle_signal)

    log.info("SIEM-Lite engine started")
    scan_interval = int(config.get('scan_interval', 10))
    last_prune = 0
    last_risk = 0
    rules = load_sigma_rules()
    last_rule_load = time.time()

    while running:
        try:
            # Reload config periodically
            config = load_config()

            # Reload rules every 60 seconds
            if time.time() - last_rule_load > 60:
                rules = load_sigma_rules()
                last_rule_load = time.time()

            # Collect new events
            new_events = collect_logs(conn, config)

            # Evaluate rules
            if new_events:
                evaluate_rules(conn, new_events, rules, config)

            # Prune every hour
            if time.time() - last_prune > 3600:
                prune_old_data(conn, config)
                last_prune = time.time()

            # Risk score every 5 minutes
            if time.time() - last_risk > 300:
                calculate_risk_score(conn, config)
                last_risk = time.time()

            time.sleep(scan_interval)

        except Exception as ex:
            log.error(f"Engine error: {ex}")
            time.sleep(5)

    conn.close()
    log.info("SIEM-Lite engine stopped")


if __name__ == '__main__':
    run_daemon()
