PLUGIN_NAME=		theme-service-hub
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Theme overlay to keep only Services Hub visible in Services menu
PLUGIN_MAINTAINER=	kuiper@local
PLUGIN_WWW=		https://opnsense.org
PLUGIN_NO_ABI=		yes

.include "../../Mk/plugins.mk"
