#!/bin/sh
#
# PROVIDE: siemlite
# REQUIRE: SERVERS
# KEYWORD: shutdown

. /etc/rc.subr

name="siemlite"
rcvar="siemlite_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-f -P ${pidfile} /usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/SIEMLite/siemlite_engine.py"

start_precmd="siemlite_prestart"
stop_postcmd="siemlite_poststop"

siemlite_prestart()
{
    mkdir -p /var/log/siemlite
    mkdir -p /var/db/siemlite
    mkdir -p /usr/local/etc/siemlite
    /usr/local/sbin/configctl template reload OPNsense/SIEMLite
}

siemlite_poststop()
{
    rm -f ${pidfile}
}

load_rc_config $name
: ${siemlite_enable="NO"}
run_rc_command "$1"
