PLUGIN_NAME=		service-hub
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Services Hub with category organisation
PLUGIN_MAINTAINER=	kuiper@local
PLUGIN_WWW=		https://opnsense.org

.include "../../Mk/plugins.mk"
