PLUGIN_NAME=		realtek-re
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	7
PLUGIN_COMMENT=		Realtek re(4) vendor driver
PLUGIN_MAINTAINER=	franco@opnsense.org
PLUGIN_DEPENDS=		realtek-re-kmod
PLUGIN_WWW=		https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software

.include "../../Mk/plugins.mk"
